In [1]:
import numpy as np
import pandas as pd
from io import StringIO
import seaborn as sns


In [2]:
lst=[1,2,3,4]
arr=np.array(lst)

In [3]:
np.array(lst)

array([1, 2, 3, 4])

In [4]:
l1=[1,2,3,4,5]
l2=[1,2,6,4,10]
l3=[1,2,8,4,9]
arr1=np.array([l1,l2,l3])

In [5]:
type(arr1)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  6,  4, 10],
       [ 1,  2,  8,  4,  9]])

In [6]:
#indexing
arr[3]


4

In [7]:
arr[::-1]


array([4, 3, 2, 1])

In [8]:
arr1[:,2]

array([3, 6, 8])

In [9]:
arr1[1:,3:]

array([[ 4, 10],
       [ 4,  9]])

In [10]:
arr1[:,0::4]

array([[ 1,  5],
       [ 1, 10],
       [ 1,  9]])

In [11]:
#EDA
arr


array([1, 2, 3, 4])

In [12]:
arr<2

array([ True, False, False, False])

In [13]:
arr[arr<2]

array([1])

In [14]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  1],
       [ 2,  6,  4],
       [10,  1,  2],
       [ 8,  4,  9]])

In [15]:
##mechanism to create an array
np.arange(1,20,2).reshape(1,10,1) 

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]])

In [16]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
arr/arr

array([1., 1., 1., 1.])

In [18]:
np.ones(2)

array([1., 1.])

In [19]:
np.random.randint(10,50,4) 

array([11, 42, 33, 19])

In [20]:
np.arange(0,40).reshape(10,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [21]:
#Creating Dataframe
df=pd.DataFrame(data=np.arange(0,40).reshape(10,4),index=['row1','row2','row3','row4','row5','row6','row7','row8','row9','row10']
                ,columns=['col1','col2','col3','col4'])

In [22]:
df

col1  col2  col3  col4
row1      0     1     2     3
row2      4     5     6     7
row3      8     9    10    11
row4     12    13    14    15
row5     16    17    18    19
row6     20    21    22    23
row7     24    25    26    27
row8     28    29    30    31
row9     32    33    34    35
row10    36    37    38    39

In [23]:
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [24]:
df.describe()

col1       col2       col3       col4
count  10.000000  10.000000  10.000000  10.000000
mean   18.000000  19.000000  20.000000  21.000000
std    12.110601  12.110601  12.110601  12.110601
min     0.000000   1.000000   2.000000   3.000000
25%     9.000000  10.000000  11.000000  12.000000
50%    18.000000  19.000000  20.000000  21.000000
75%    27.000000  28.000000  29.000000  30.000000
max    36.000000  37.000000  38.000000  39.000000

In [25]:
#Indexing
## Columnname, rowindex[loc],rowindex columnindex number[.iloc]
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [26]:
#columname
df[['col1','col2','col3']]

col1  col2  col3
row1      0     1     2
row2      4     5     6
row3      8     9    10
row4     12    13    14
row5     16    17    18
row6     20    21    22
row7     24    25    26
row8     28    29    30
row9     32    33    34
row10    36    37    38

In [27]:
df[3::4]

col1  col2  col3  col4
row4    12    13    14    15
row8    28    29    30    31

In [28]:
df['col1']

row1      0
row2      4
row3      8
row4     12
row5     16
row6     20
row7     24
row8     28
row9     32
row10    36
Name: col1, dtype: int32

In [29]:
type(df['col1'])

pandas.core.series.Series

In [30]:
type(df[['col1','col2','col3']])

pandas.core.frame.DataFrame

In [31]:
df.loc['row4']

col1    12
col2    13
col3    14
col4    15
Name: row4, dtype: int32

In [32]:
##using row index name loc
df.loc[['row1','row2','row5']]

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row5    16    17    18    19

In [33]:
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [34]:
df.iloc[2:4,0:2]

col1  col2
row3     8     9
row4    12    13

In [35]:
df.iloc[0:5,0:4:3]

col1  col4
row1     0     3
row2     4     7
row3     8    11
row4    12    15
row5    16    19

In [36]:
#convert df into arr
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23],
       [25, 26, 27],
       [29, 30, 31],
       [33, 34, 35],
       [37, 38, 39]])

In [37]:
#operations
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [38]:
df.isnull()

col1   col2   col3   col4
row1   False  False  False  False
row2   False  False  False  False
row3   False  False  False  False
row4   False  False  False  False
row5   False  False  False  False
row6   False  False  False  False
row7   False  False  False  False
row8   False  False  False  False
row9   False  False  False  False
row10  False  False  False  False

In [39]:
df1=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=['row1','row2']
                ,columns=['col1','col2','col3'])

In [40]:
df1

col1  col2  col3
row1     1   NaN     2
row2     1   3.0     4

In [41]:
df1.isnull()

col1   col2   col3
row1  False   True  False
row2  False  False  False

In [42]:
df1.isnull().sum()==0

col1     True
col2    False
col3     True
dtype: bool

In [43]:
df1['col2'].value_counts()

col2
3.0    1
Name: count, dtype: int64

In [44]:
df['col3'].unique()

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38])

In [45]:
df2 = pd.read_csv(r"C:\Users\karan\Downloads\mercedesbenz.csv")


In [46]:
df2.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [47]:
data=('col1,col2,col3\n'
     'x,y,1\n'
     'a,b,2\n'
     'c,d,3')

In [48]:
type(data)

str

In [49]:
##in memory file format object
StringIO(data)

In [50]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [51]:
data1=('a,b,c\n'
       '4,apple,bat,5.7\n'
       '8,orange,cow,10')

In [52]:
pd.read_csv(StringIO(data1))

a    b     c
4   apple  bat   5.7
8  orange  cow  10.0

In [53]:
##use index cols and usecols
pd.read_csv(StringIO(data1),usecols=['a','b','c'],index_col=0)

b    c
a             
4   apple  bat
8  orange  cow

In [54]:
pd.read_csv(r'C:\Users\karan\Downloads\cu.item' , sep='\t')

item_code                                          item_name  \
0         AA0                               All items - old base   
1        AA0R  Purchasing power of the consumer dollar - old ...   
2         SA0                                          All items   
3        SA0E                                             Energy   
4       SA0L1                                All items less food   
..        ...                                                ...   
395   SSEA011                                  College textbooks   
396   SSEE041                                        Smartphones   
397  SSFV031A           Food at elementary and secondary schools   
398   SSGE013                                 Infants' equipment   
399   SSHJ031                                 Infants' furniture   

     display_level selectable  sort_sequence  
0                0          T              2  
1                0          T            400  
2                0          T              1  
3                1          T            375  
4                1          T            359  
..             ...        ...            ...  
395              3          T            314  
396              4          T            335  
397              3          T            122  
398              3          T            356  
399              3          T            165  

[400 rows x 5 columns]

In [55]:
data3='{"emp_name":"janu","email":"janu@gmail.com","job_profile":[{"title1":"Team Lead","title2":"Sr. Developer"}]}'

In [56]:
type(data3)

str

In [57]:
data3

'{"emp_name":"janu","email":"janu@gmail.com","job_profile":[{"title1":"Team Lead","title2":"Sr. Developer"}]}'

In [58]:
pd.read_json(data3)

emp_name           email                                        job_profile
0     janu  janu@gmail.com  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [59]:
#json orient uses
pd.read_json(data3, orient='records')

emp_name           email                                        job_profile
0     janu  janu@gmail.com  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [60]:
df=pd.DataFrame([['a','b'],['c','d']],
                index=['row1','row2'],
                columns=['col1','col2'])       

In [61]:
df

col1 col2
row1    a    b
row2    c    d

In [62]:
df.to_json()

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [63]:
df.to_json(orient='columns')

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [64]:
df.to_json(orient='index')

'{"row1":{"col1":"a","col2":"b"},"row2":{"col1":"c","col2":"d"}}'

In [65]:
df.to_json(orient='records')

'[{"col1":"a","col2":"b"},{"col1":"c","col2":"d"}]'

In [66]:
df.to_json(orient='split')

'{"columns":["col1","col2"],"index":["row1","row2"],"data":[["a","b"],["c","d"]]}'

In [67]:
df.to_json(orient='table')

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col1","type":"string"},{"name":"col2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row1","col1":"a","col2":"b"},{"index":"row2","col1":"c","col2":"d"}]}'

In [68]:
#normalize json data
data3=[{"emp_name":"janu","email":"janu@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]

In [69]:
type(data3)

list

In [70]:
pd.json_normalize(data3)

emp_name           email job_profile.title1 job_profile.title2
0     janu  janu@gmail.com          Team Lead      Sr. Developer

In [71]:
data4 = [
    {
         "id": 1,
        "name": "Cole Volk",
         "fitness": {"height": 130, "weight": 60},
    },
     {"name": "Mark Reg", "fitness": {"height": 130, "weight": 60}},
     {
         "id": 2,
       "name": "Faye Raker",
        "fitness": {"height": 130, "weight": 60},
    },
]

In [72]:
pd.json_normalize(data4)

id        name  fitness.height  fitness.weight
0  1.0   Cole Volk             130              60
1  NaN    Mark Reg             130              60
2  2.0  Faye Raker             130              60

In [73]:
data5 = [
     {
         "state": "Florida",
         "shortname": "FL",
         "info": {"governor": "Rick Scott"},
         "counties": [
             {"name": "Dade", "population": 12345},
             {"name": "Broward", "population": 40000},
             {"name": "Palm Beach", "population": 60000},
         ],
     },
       {
         "state": "Ohio",
         "shortname": "OH",
         "info": {"governor": "John Kasich"},
         "counties": [
             {"name": "Summit", "population": 1234},
             {"name": "Cuyahoga", "population": 1337},
         ],
     },
 ]

In [74]:
pd.json_normalize(data5)

state shortname                                           counties  \
0  Florida        FL  [{'name': 'Dade', 'population': 12345}, {'name...   
1     Ohio        OH  [{'name': 'Summit', 'population': 1234}, {'nam...   

  info.governor  
0    Rick Scott  
1   John Kasich

In [75]:
pd.json_normalize(data5, "counties",["state","shortname",["info",'governor']])

name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

In [76]:
##read HTML
html=pd.read_html(r"https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")


In [77]:
html

[    Symbol            Security             GICS Sector  \
 0      MMM                  3M             Industrials   
 1      AOS         A. O. Smith             Industrials   
 2      ABT              Abbott             Health Care   
 3     ABBV              AbbVie             Health Care   
 4      ACN           Accenture  Information Technology   
 ..     ...                 ...                     ...   
 498    XYL          Xylem Inc.             Industrials   
 499    YUM         Yum! Brands  Consumer Discretionary   
 500   ZBRA  Zebra Technologies  Information Technology   
 501    ZBH       Zimmer Biomet             Health Care   
 502    ZTS              Zoetis             Health Care   
 
                                 GICS Sub-Industry    Headquarters Location  \
 0                        Industrial Conglomerates    Saint Paul, Minnesota   
 1                               Building Products     Milwaukee, Wisconsin   
 2                           Health Care Equipment  N

In [78]:
type(html)

list

In [79]:
html[0]

Symbol            Security             GICS Sector  \
0      MMM                  3M             Industrials   
1      AOS         A. O. Smith             Industrials   
2      ABT              Abbott             Health Care   
3     ABBV              AbbVie             Health Care   
4      ACN           Accenture  Information Technology   
..     ...                 ...                     ...   
498    XYL          Xylem Inc.             Industrials   
499    YUM         Yum! Brands  Consumer Discretionary   
500   ZBRA  Zebra Technologies  Information Technology   
501    ZBH       Zimmer Biomet             Health Care   
502    ZTS              Zoetis             Health Care   

                                GICS Sub-Industry    Headquarters Location  \
0                        Industrial Conglomerates    Saint Paul, Minnesota   
1                               Building Products     Milwaukee, Wisconsin   
2                           Health Care Equipment  North Chicago, Illinois   
3                                   Biotechnology  North Chicago, Illinois   
4                  IT Consulting & Other Services          Dublin, Ireland   
..                                            ...                      ...   
498  Industrial Machinery & Supplies & Components   White Plains, New York   
499                                   Restaurants     Louisville, Kentucky   
500            Electronic Equipment & Instruments   Lincolnshire, Illinois   
501                         Health Care Equipment          Warsaw, Indiana   
502                               Pharmaceuticals   Parsippany, New Jersey   

     Date added      CIK      Founded  
0    1957-03-04    66740         1902  
1    2017-07-26    91142         1916  
2    1957-03-04     1800         1888  
3    2012-12-31  1551152  2013 (1888)  
4    2011-07-06  1467373         1989  
..          ...      ...          ...  
498  2011-11-01  1524472         2011  
499  1997-10-06  1041061         1997  
500  2019-12-23   877212         1969  
501  2001-08-07  1136869         1927  
502  2013-06-21  1555280         1952  

[503 rows x 8 columns]

In [80]:
html[0].to_html('demo.html')

In [81]:
 ##read xml 
xml=pd.read_xml('test.xml')

In [82]:
xml

id firstName lastName  certificate  scores  ind
0  1.0      Greg     Dean         True     NaN  NaN
1  NaN      Wirt     Wood         True     NaN  2.0

Pickle in python is primarily used in serializing and desearilizing a python object string in other words.Its the process of converting a python object into a byte stream to store it in file/database, maintain program state across sessions or transport data over the network

In [83]:
df=sns.load_dataset('tips')

In [84]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [85]:
import pickle

In [86]:
filename='file.pkl'

In [87]:
##serialize process
pickle.dump(df,open(filename,'wb'))

In [88]:
##unserialize
df=pickle.load(open(filename,'rb'))

In [89]:
type(df)

pandas.core.frame.DataFrame